server:
    port: 8888
    servlet:
        context-path: /nepm
        
logging:
    level:
        # org.springframework: debug
        com.neusoft.nepm.mapper: debug   
        
spring:       
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/nep?characterEncoding=utf-8
        username: root
        password: 1234     
        
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.neusoft.nepm.po
    
        
